# Generated by Django 4.1.5 on 2023-03-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_remove_bank_branches_branch_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='institutionnumber',
            new_name='inst_num',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='swiftcode',
            new_name='swift_code',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='transitnumber',
            new_name='transit_num',
        ),
    ]
