# Generated by Django 4.1.5 on 2023-03-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_rename_institutionnumber_bank_inst_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
